Focus View (GitHub only)
gitkraken/gk-browser-extension pull request #28
Opened 2024-04-13 00:15 UTC by jdgarcia

The signed out and user row (when signed in) UIs have been redone

Focus View only shows up if you have GitHub connected, otherwise it's just a blank screen (for now, next PR will be "connect an integration" UI).

2024-04-15 17:42 UTC, gitkrakel requested changes
### Layout on Firefox ESR (115.x) is completely broken

<details>
<summary>Sign-in page</summary>

![Screenshot from 2024-04-15 10-25-01](https://github.com/gitkraken/gk-browser-extension/assets/102260814/6ad08faa-54b1-4996-a3a9-5ef09c1392d0)
</details>

<details>
<summary>Focus View</summary>

![Screenshot from 2024-04-15 10-31-54](https://github.com/gitkraken/gk-browser-extension/assets/102260814/5c8b4e73-0f51-40ae-885d-2e50d9b320a2)
</details>

### (optional) Nits with layout when permissions are requested

<details>
<summary>Scrollbar in Focus View when permissions are requested</summary>

![Screenshot from 2024-04-15 10-35-20](https://github.com/gitkraken/gk-browser-extension/assets/102260814/445ff55e-57e9-4170-8aad-5d0649c82fc8)
</details>

<details>
<summary>Unnecessary word wrap when cloud and self-hosted are both requested</summary>

![Screenshot from 2024-04-15 10-36-40](https://github.com/gitkraken/gk-browser-extension/assets/102260814/13f462d1-6b8d-489c-a637-d40df2a40315)
</details>

2024-04-16 15:48 UTC, jdgarcia commented
@gitkrakel well, the good news is that the layout is broken simply because Firefox ESR doesn't support nested CSS. The bad news is I can't use nested CSS which I was happy to be able to use 😢 

> Scrollbar in Focus View when permissions are requested

That's intentional. The popup has a max height enforced by the browser, and I opted to make the permission banner and the user bar static, and everything else scrollable.

> Unnecessary word wrap when cloud and self-hosted are both requested

That's a consequence of the font size and weight used in the Figma design.

2024-04-16 16:51 UTC, jdgarcia commented on src/popup/components/FocusView.tsx
> +			const providerClient = new GitHub({ token: githubToken.accessToken });
I'm gonna have to update this almost immediately anyway, I don't think it matters if it's in this PR or the next.

2024-04-16 16:59 UTC, gitkrakel commented
@jdgarcia So I looked into CSS nesting more, and a couple notes:

1. The current Firefox ESR does in fact support nesting, but it's disabled by default. The user needs to go into `about:config` -> `layout.css.nesting.enabled` to toggle it on, and then the Focus View seems to work as intended:

![image](https://github.com/gitkraken/gk-browser-extension/assets/102260814/3ea8355c-704c-43ff-ba9e-7c1e4682af3c)

2. CSS nesting is enabled by default starting in Firefox 117: https://www.mozilla.org/en-US/firefox/117.0/releasenotes/. Therefore, regular releases of Firefox already support it
3. The next Firefox ESR is 128.0, which comes out in July 2024 (https://whattrainisitnow.com/calendar/). So if CSS nesting is something you feel strongly about, I think it's fine to compromise and tell Firefox ESR 115 users to enable the `about:config` flag (they should be a small fraction of the userbase anyway)

2024-04-16 20:59 UTC, merged